# Generated by Django 5.2.3 on 2025-06-30 07:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a main profile picture for the artisan.', null=True, upload_to='artisans/')),
                ('name', models.CharField(help_text='Full name of the artisan.', max_length=100)),
                ('job_title', models.CharField(help_text='e.g., Plumber, Electrician, Carpenter.', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Primary phone number for contact.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address for business inquiries.', max_length=254, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location or service area.', max_length=200, null=True)),
                ('business_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='A brief description of their business.', null=True)),
                ('products_services', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed list of products/services offered.', null=True)),
                ('working_hours', models.CharField(blank=True, help_text='e.g., Mon-Fri: 9 AM - 5 PM, Sat: 10 AM - 2 PM.', max_length=200, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating based on reviews (e.g., 4.5).', max_digits=3)),
                ('num_reviews', models.IntegerField(default=0, help_text='Total number of reviews received.')),
            ],
            options={
                'verbose_name': 'Artisan',
                'verbose_name_plural': 'Artisans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('roles_responsibilities', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Community Info',
            },
        ),
        migrations.CreateModel(
            name='CommunityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Community Policies',
            },
        ),
        migrations.CreateModel(
            name='Defaulter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='defaulter_images/')),
                ('name', models.CharField(max_length=100)),
                ('cda', models.CharField(choices=[('Unity CDA', 'Unity CDA'), ('Harmony CDA', 'Harmony CDA'), ('Valley-View CDA', 'Valley-View CDA')], max_length=100, verbose_name='CDA')),
                ('amount_indebted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title_defaulted', models.CharField(choices=[('Security Fees', 'Security Fees'), ('Electricity', 'Electricity'), ('Development Levy', 'Development Levy'), ('Others', 'Others')], max_length=200, verbose_name='Debt For:')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('In Progress', 'In Progress'), ('Indebt', 'Indebt')], default='Pending', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text', models.TextField(help_text='Text to display in the footer')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NavbarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='navbar_images/')),
                ('position', models.CharField(choices=[('left', 'Left Corner'), ('right', 'Right Corner')], max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='paid_member_images/')),
                ('name', models.CharField(max_length=100)),
                ('cda', models.CharField(choices=[('Unity CDA', 'Unity CDA'), ('Harmony CDA', 'Harmony CDA'), ('Valley-View CDA', 'Valley-View CDA')], max_length=100, verbose_name='CDA')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose_of_payment', models.CharField(choices=[('Security Fees', 'Security Fees'), ('Electricity', 'Electricity'), ('Development Levy', 'Development Levy'), ('Others', 'Others')], max_length=200, verbose_name='Purpose of Payment')),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload a main profile picture for the professional.', null=True, upload_to='professionals/')),
                ('name', models.CharField(help_text='Full name of the professional.', max_length=100)),
                ('job_title', models.CharField(help_text='e.g., Accountant, Lawyer, Architect.', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Primary phone number for contact.', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address for business inquiries.', max_length=254, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location or service area.', max_length=200, null=True)),
                ('business_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='A brief description of their professional service.', null=True)),
                ('products_services', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed list of services offered.', null=True)),
                ('working_hours', models.CharField(blank=True, help_text='e.g., Mon-Fri: 9 AM - 5 PM.', max_length=200, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating based on reviews (e.g., 4.8).', max_digits=3)),
                ('num_reviews', models.IntegerField(default=0, help_text='Total number of reviews received.')),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDonationModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_donation_images/')),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text', django_ckeditor_5.fields.CKEditor5Field()),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter (X)'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], default='tenant', max_length=10)),
                ('cda', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('is_approved', models.BooleanField(default=False)),
                ('last_approval_email_sent', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('For Lease', 'For Lease')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('advert_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cda_app.advertitem')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('willing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cda_app.advertitem')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_emails_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Email Log',
                'verbose_name_plural': 'Approval Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Upload an image for the artisan's gallery.", upload_to='artisan_galleries/')),
                ('description', models.CharField(blank=True, help_text='Optional description for the image.', max_length=255, null=True)),
                ('artisan', models.ForeignKey(help_text='The artisan this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cda_app.artisan')),
            ],
            options={
                'verbose_name': 'Artisan Gallery Image',
                'verbose_name_plural': 'Artisan Gallery Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayCelebrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='celebrant_images/')),
                ('date_of_birth', models.DateField()),
                ('admin_wishes', django_ckeditor_5.fields.CKEditor5Field()),
                ('last_celebrated_year', models.IntegerField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday Celebrant',
                'verbose_name_plural': 'Birthday Celebrants',
            },
        ),
        migrations.CreateModel(
            name='CommitteeAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='cda_app.committee')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee_members/')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cda_app.committee')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='cda_app.committee')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='executive_members/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cda_app.cda')),
            ],
        ),
        migrations.CreateModel(
            name='Levy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levy_type', models.CharField(choices=[('Development Fees', 'Development Fees'), ('Others', 'Others'), ('Electricity', 'Electricity'), ('Security Fees', 'Security Fees')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('cda', models.ForeignKey(blank=True, help_text='Leave blank for joint payments (Electricity, Security Fees)', null=True, on_delete=django.db.models.deletion.CASCADE, to='cda_app.cda')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Upload an image for the professional's gallery.", upload_to='professional_galleries/')),
                ('description', models.CharField(blank=True, help_text='Optional description for the image.', max_length=255, null=True)),
                ('professional', models.ForeignKey(help_text='The professional this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cda_app.professional')),
            ],
            options={
                'verbose_name': 'Professional Gallery Image',
                'verbose_name_plural': 'Professional Gallery Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DonationProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator_name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('donated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_receipt_image', models.ImageField(upload_to='donation_proofs/')),
                ('donation_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_proofs', to='cda_app.projectdonation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cda_app.projectdonation')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='cda_app.advertitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('levy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cda_app.levy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_levy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cda_app.userlevy')),
            ],
        ),
        migrations.CreateModel(
            name='WellWishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celebrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_wishes', to='cda_app.birthdaycelebrant')),
            ],
            options={
                'verbose_name': 'Well Wish',
                'verbose_name_plural': 'Well Wishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellWishReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cda_app.wellwishes')),
            ],
            options={
                'verbose_name_plural': 'Well Wish Replies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegularLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select the month for this levy', max_length=20, verbose_name='Month')),
                ('year', models.PositiveIntegerField(help_text='Enter the year for this levy', verbose_name='Year')),
                ('payment_for', models.CharField(choices=[('Electricity', 'Electricity'), ('Security', 'Security'), ('Development Levies', 'Development Levies'), ('Sanitations', 'Sanitations'), ('Others', 'Others')], help_text='Select the purpose of this payment', max_length=50, verbose_name='Payment For')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the amount to be paid', max_digits=10, verbose_name='Amount')),
                ('cda', models.CharField(help_text='Community Development Association', max_length=100, verbose_name='CDA')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='unpaid', help_text='Current payment status', max_length=20, verbose_name='Status')),
                ('proof_of_payment', models.ImageField(blank=True, help_text='Upload proof of payment', null=True, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Proof of Payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levies', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Regular Levy',
                'verbose_name_plural': 'Regular Levies',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'month', 'year', 'payment_for'), name='unique_user_levy_per_month')],
            },
        ),
    ]
