# Generated by Django 5.2.3 on 2025-06-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short title for the banner (e.g., 'Discount Offer').", max_length=200)),
                ('image', models.ImageField(help_text='Upload the banner image.', upload_to='banners/')),
                ('target_url', models.URLField(blank=True, help_text='Optional: URL to navigate to when the banner is clicked (e.g., a product page).', max_length=500, null=True)),
                ('position', models.CharField(choices=[('left', 'Left Sidebar'), ('right', 'Right Sidebar')], help_text='Where this banner will be displayed on the page. Only one banner per position.', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check to make this banner active and visible on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Banner',
                'verbose_name_plural': 'Website Banners',
                'ordering': ['position'],
            },
        ),
    ]
