# Generated by Django 5.2.3 on 2025-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='birthday_wishes/logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='birthday_wishes/images/')),
                ('heading', models.CharField(default='Happy Birthday', max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('wishes_text', models.TextField()),
                ('frame_background', models.ImageField(blank=True, null=True, upload_to='birthday_wishes/backgrounds/')),
            ],
        ),
    ]
