# Generated by Django 5.2.3 on 2025-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cda_app', '0003_birthdaywish'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('donator_name', models.CharField(max_length=255)),
                ('donated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='special_donation_receipts/')),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Donation',
                'verbose_name_plural': 'Special Donations',
                'ordering': ['-donation_date'],
            },
        ),
    ]
